package fi.nutrifier.models.room

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity class representing a personal recipe stored in the 'personal_recipes' table of the Room database.
 *
 * @property title The title of the recipe.
 * @property image The image URL of the recipe.
 * @property servings The number of servings the recipe yields.
 * @property ingredients The list of ingredients used in the recipe.
 * @property instructions The list of instructions to prepare the recipe.
 * @property id The unique identifier of the recipe (auto-generated by Room).
 */
@Entity(tableName = "personal_recipes")
data class PersonalRecipe(
    val title: String,
    val image: String,
    val servings: Double,
    val ingredients: List<RecipeIngredient>,
    val instructions: List<RecipeInstruction>,
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
)
